-- Baseline schema for Motivora.
-- Generated from the JPA entity model (Hibernate) so that `ddl-auto: validate` passes.

create table authors (
    id integer generated by default as identity,
    is_active boolean not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    avatar_url varchar(255),
    bio varchar(255),
    name varchar(255) not null,
    slug varchar(255),
    primary key (id)
);

create table favorites (
    id integer generated by default as identity,
    quote_id integer not null,
    user_id integer not null,
    created_at timestamp(6),
    primary key (id),
    constraint uq_favorite_user_quote unique (user_id, quote_id)
);

create table jwts (
    expire boolean not null,
    id integer generated by default as identity,
    refresh_token_id integer unique,
    user_id integer,
    created_at timestamp(6),
    expire_at timestamp(6) with time zone,
    token TEXT,
    primary key (id)
);

create table notifications (
    id integer generated by default as identity,
    is_read boolean,
    user_id integer,
    created_at timestamp(6),
    updated_at timestamp(6),
    message varchar(255) not null,
    title varchar(255),
    primary key (id)
);

create table otp_codes (
    id integer generated by default as identity,
    user_id integer unique,
    confirmed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone,
    otp varchar(255),
    primary key (id)
);

create table quotes (
    author_id integer,
    created_by_user_id integer,
    id integer generated by default as identity,
    theme_id integer not null,
    created_at timestamp(6),
    published_at timestamp(6),
    updated_at timestamp(6),
    content varchar(255) not null,
    slug varchar(255) not null,
    status varchar(255) check (status in ('DRAFT','PUBLISHED','ARCHIVED','DELETED','REVIEW_PENDING','REJECTED','DISABLE')),
    primary key (id),
    constraint idx_quote_slug unique (slug)
);

create table refresh_tokens (
    expire boolean not null,
    id integer generated by default as identity,
    created_at timestamp(6) with time zone,
    expire_at timestamp(6) with time zone,
    token varchar(255),
    primary key (id)
);

create table roles (
    id integer generated by default as identity,
    name varchar(255) not null unique check (name in ('USER','ADMIN','MODERATOR','CREATOR')),
    primary key (id)
);

create table tags (
    id integer generated by default as identity,
    created_at timestamp(6),
    updated_at timestamp(6),
    name varchar(255) not null unique,
    primary key (id)
);

create table themes (
    id integer generated by default as identity,
    is_active boolean not null,
    color varchar(255),
    description varchar(255),
    image_url varchar(255),
    name varchar(255) not null,
    slug varchar(255) not null unique,
    primary key (id)
);

create table users (
    id integer generated by default as identity,
    role_id integer not null,
    created_at timestamp(6),
    email_verified_at timestamp(6),
    updated_at timestamp(6),
    email varchar(255) not null unique,
    password varchar(255) not null,
    pseudo varchar(255),
    status varchar(255) check (status in ('ACTIVE','INACTIVE','SUSPENDED','DELETED')),
    primary key (id)
);

create index idx_author_slug on authors (slug);
create index idx_quote_status on quotes (status);
create index idx_quote_theme on quotes (theme_id);
create index idx_quote_author on quotes (author_id);
create index idx_theme_slug_name_active on themes (slug, name, is_active);

alter table if exists favorites
    add constraint fk_favorite_quote foreign key (quote_id) references quotes;
alter table if exists favorites
    add constraint fk_favorite_user foreign key (user_id) references users;
alter table if exists jwts
    add constraint fk_jwt_refresh_token foreign key (refresh_token_id) references refresh_tokens;
alter table if exists jwts
    add constraint fk_jwt_user foreign key (user_id) references users;
alter table if exists notifications
    add constraint fk_notification_user foreign key (user_id) references users;
alter table if exists otp_codes
    add constraint fk_otp_user foreign key (user_id) references users;
alter table if exists quotes
    add constraint fk_quote_author foreign key (author_id) references authors;
alter table if exists quotes
    add constraint fk_quote_created_by_user foreign key (created_by_user_id) references users;
alter table if exists quotes
    add constraint fk_quote_theme foreign key (theme_id) references themes;
alter table if exists users
    add constraint fk_user_role foreign key (role_id) references roles;
