-- Phase C: daily push notifications.
--   1. Device tokens: where a push is actually delivered (one row per install).
--   2. Notification preferences: whether, when and in which timezone a user is notified.
--   3. Followed themes: what the daily quote is drawn from.
--   4. The existing notifications table becomes the in-app history.

-- 1. Device tokens ------------------------------------------------------------
create table device_tokens (
    id integer generated by default as identity,
    user_id integer not null,
    token varchar(255) not null,
    platform varchar(20) not null,
    device_id varchar(100),
    device_name varchar(120),
    enabled boolean not null default true,
    last_used_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uq_device_token unique (token),
    constraint fk_device_token_user foreign key (user_id) references users
);

create index idx_device_token_user on device_tokens (user_id, enabled);

-- 2. Notification preferences -------------------------------------------------
create table notification_preferences (
    id integer generated by default as identity,
    user_id integer not null,
    daily_quote_enabled boolean not null default true,
    -- Local hour of day the daily quote is sent, in the user's own timezone.
    daily_quote_hour integer not null default 8,
    timezone varchar(64) not null default 'UTC',
    last_sent_on date,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uq_notification_preference_user unique (user_id),
    constraint fk_notification_preference_user foreign key (user_id) references users
);

-- Everyone starts opted in at 08:00 UTC; the app asks for the OS permission separately.
insert into notification_preferences (user_id, daily_quote_enabled, daily_quote_hour, timezone)
select id, true, 8, 'UTC' from users;

-- 3. Followed themes ----------------------------------------------------------
create table user_followed_themes (
    user_id integer not null,
    theme_id integer not null,
    primary key (user_id, theme_id),
    constraint fk_followed_theme_user foreign key (user_id) references users,
    constraint fk_followed_theme_theme foreign key (theme_id) references themes
);

-- 4. In-app notification history ---------------------------------------------
alter table notifications add column type varchar(40);
alter table notifications add column quote_id integer;
alter table notifications add column read_at timestamp(6);
update notifications set type = 'SYSTEM' where type is null;
alter table notifications alter column type set not null;
alter table notifications alter column is_read set default false;
alter table notifications
    add constraint fk_notification_quote foreign key (quote_id) references quotes;

create index idx_notification_user_created on notifications (user_id, created_at desc);
